"""Tool + registry tests: `create_document`.

`create_document` mints a blank, tracked working-copy document from a width/height (+ optional
viewBox / background) with NO source file, returns the SAME `{doc_id, summary}` shape as
`open_document`, and the result is `validate_document`-clean. These tests are hermetic (direct DOM
only — no Inkscape).
"""

from __future__ import annotations

import asyncio
from pathlib import Path

import pytest
from fastmcp.exceptions import ToolError

from inkscape_mcp.config import ENV_WORKSPACE_ROOTS, get_settings
from inkscape_mcp.registry import get_registry, reset_registry
from inkscape_mcp.server import mcp
from inkscape_mcp.tools.document import OpenDocumentResult, create_document
from inkscape_mcp.validate import validate_document
from inkscape_mcp.workspace import sandbox


@pytest.fixture
def root(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    ws = tmp_path / "ws"
    ws.mkdir()
    monkeypatch.setenv(ENV_WORKSPACE_ROOTS, str(ws))
    get_settings.cache_clear()
    reset_registry()
    return ws


def test_create_document_returns_open_document_shape(root: Path) -> None:
    result = create_document(width=120, height=80)
    assert isinstance(result, OpenDocumentResult)
    assert result.doc_id.startswith("d_")
    assert result.summary.root_tag == "svg"
    assert result.summary.width == "120"
    assert result.summary.height == "80"
    # No explicit viewBox -> synthesized `0 0 W H` so the doc is never viewBox-less.
    assert result.summary.viewbox == [0.0, 0.0, 120.0, 80.0]


def test_create_document_is_validate_clean(root: Path) -> None:
    result = create_document(width=64, height=64)
    report = validate_document(result.doc_id)
    assert report.ok
    assert report.error_count == 0


def test_create_document_explicit_viewbox(root: Path) -> None:
    result = create_document(width=100, height=100, viewBox="0 0 200 50")
    assert result.summary.viewbox == [0.0, 0.0, 200.0, 50.0]


def test_create_document_with_background_rect(root: Path) -> None:
    result = create_document(width=40, height=40, background="#3366cc")
    entry = get_registry().get(result.doc_id)
    working = Path(entry.working_path).read_text(encoding="utf-8")
    assert 'id="background"' in working
    assert "#3366cc" in working
    # Still validate-clean with the background rect present.
    assert validate_document(result.doc_id).ok


def test_create_document_seeds_original_and_working(root: Path) -> None:
    """A created doc has both original.svg (the reload seed) and working/document.svg seeded."""
    result = create_document(width=10, height=10)
    entry = get_registry().get(result.doc_id)
    original = sandbox.original_copy(root, result.doc_id)
    working = sandbox.working_copy(root, result.doc_id)
    assert original.is_file()
    assert working.is_file()
    # Both seeded from the SAME generated bytes.
    assert original.read_bytes() == working.read_bytes()
    # No external source file is referenced; the conventional name is used.
    assert entry.source_path == "document.svg"


def test_create_document_rejects_non_positive_size(root: Path) -> None:
    with pytest.raises(ToolError) as exc:
        create_document(width=0, height=50)
    assert "greater than 0" in str(exc.value)


def test_create_document_rejects_bad_viewbox(root: Path) -> None:
    with pytest.raises(ToolError) as exc:
        create_document(width=10, height=10, viewBox="not four numbers")
    assert "viewBox" in str(exc.value)


def test_create_document_rejects_injection_background(root: Path) -> None:
    """A CSS-injection background colour is rejected (normalize_color guards punctuation)."""
    with pytest.raises(ToolError):
        create_document(width=10, height=10, background="red;stroke:url(http://evil)")


def test_create_document_registered_on_mcp(root: Path) -> None:
    names = {tool.name for tool in asyncio.run(mcp.list_tools())}
    assert "create_document" in names
